# Dependabot will run on day 3 of each month at 02:47 (Europe/Berlin timezone)
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: "production"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "47 2 3 * *"
    open-pull-requests-limit: 20
    assignees:
      - "crycode-de"
    versioning-strategy: "increase"
